name: Call GitHub API

on:
  workflow_dispatch:

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Call GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/octocat/Spoon-Knife/issues
